apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello
  namespace: python-hello
  labels:
    app: python-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-hello
  strategy: {}
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
      - name: python-hello
        image: python-hello:v1.0.0
        ports:
          - containerPort: 5000
        resources: {}
